

include $(GOROOT)/src/Make.inc

TARG=refactoring/refactoring
GOFILES=\
	common.go\
	extractInterface.go\
	extractMethod.go\
	implementInterface.go\
	inlineMethod.go\
	rename.go\
	sort.go 

include $(GOROOT)/src/Make.pkg


