

include $(GOROOT)/src/Make.inc

TARG=refactoring/printerUtil
GOFILES=\
	printer.go\
	fixPositionsVisitor.go\
	findNodeVisitor.go\
	deleteNodeVisitor.go\
	reparseFile.go\

include $(GOROOT)/src/Make.pkg
