#!/bin/bash
./formatAll
cd ../src/st
gomake nuke
gomake install
cd ../utils
gomake nuke
gomake install
cd ../errors
gomake nuke
gomake install
cd ../packageParser
gomake nuke
gomake install
cd ../program
gomake nuke
gomake install
cd ../printerUtil
gomake nuke
gomake install
cd ../refactoring
gomake nuke
gomake install
cd ../main
gomake nuke
gomake install
