#!/bin/bash
8g -o ../bin/st.8 ../src/st/symbolTable.go ../src/st/symbols.go ../src/st/symbolBuilder.go ../src/st/astUtil.go
8g -o ../bin/utils.8 ../src/utils/utils.go

8g -I ../bin -o ../bin/errors.8 ../src/errors/errors.go

8g -I ../bin -o ../bin/packageParser.8 ../src/packageParser/packageParser.go ../src/packageParser/typesVisitor.go ../src/packageParser/methodsVisitor.go ../src/packageParser/globalsVisitor.go ../src/packageParser/globalsFixVisitor.go ../src/packageParser/parseExpr.go ../src/packageParser/parseExprRef.go ../src/packageParser/localsVisitor.go

8g -I ../bin -o ../bin/program.8 ../src/program/program.go ../src/program/importsVisitor.go ../src/program/findIdentVisitor.go

8g -I ../bin -o ../bin/refactoring.8 ../src/refactoring/rename.go ../src/refactoring/extractMethod.go ../src/refactoring/inlineMethod.go

#8g -I ../bin -o ../bin/test.8 ../src/tests/testRun.go
8g -I ../bin -o ../bin/print.8 ../src/tests/printTree.go
8g -I ../bin -o ../bin/goref.8 ../src/main/goref.go
#8l -L ../bin -o ../bin/test ../bin/test.8
8l -L ../bin -o ../bin/print ../bin/print.8
8l -L ../bin -o ../bin/goref ../bin/goref.8

sudo cp ../bin/goref /usr/bin