#!/bin/bash
goref inm /home/rulerr/goRefactor/src/utils/utils.go 12 9 12 25
./build

echo expression
goref exm /home/rulerr/goRefactor/src/packageParser/localsVisitor.go 235 30 235 35 SomeMeth2
goref inm /home/rulerr/goRefactor/src/packageParser/localsVisitor.go 235 30 235 41
echo multivalue
goref exm /home/rulerr/goRefactor/src/refactoring/extractMethod.go 194 10 194 82 ARRRRR
goref inm /home/rulerr/goRefactor/src/refactoring/extractMethod.go 194 10 194 18