#!/bin/bash
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go vt
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go t
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go vtfmc
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go fcs
goref sort -t /home/rulerr/goRefactor/src/packageParser/localsVisitor.go cv