

include $(GOROOT)/src/Make.inc

TARG=refactoring/packageParser
GOFILES=\
	packageParser.go\
	globalsFixVisitor.go\
	globalsVisitor.go\
	localsVisitor.go\
	methodsVisitor.go\
	parseExpr.go\
	parseExprRef.go\
	typesVisitor.go\

include $(GOROOT)/src/Make.pkg
